workflows:
  android-debug:
    name: Android Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      android_signing:
        - debug_keystore
      groups:
        - google_play
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - user@example.com
      scripts:
        - name: Notify
          script: |
            echo "Build completed!"
